export const GET_CITIES_REQUEST = 'GET_CITIES_REQUEST';
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS';
export const GET_CITIES_FAIL = 'GET_CITIES_FAIL';
export const SELECT_CITY = 'SELECT_CITY';
export const UNSELECT_CITY = 'UNSELECT_CITY';
export const GET_CITY_WEATHER_REQUEST = 'GET_CITY_WEATHER_REQUEST';
export const GET_CITY_WEATHER_SUCCESS = 'GET_CITY_WEATHER_SUCCESS';
export const GET_CITY_WEATHER_FAIL = 'GET_CITY_WEATHER_FAIL';